services:
  myshoppinglist.webapi:
    image: ${DOCKER_REGISTRY-}myshoppinglistwebapi
    build:
      context: .
      dockerfile: MyShoppingList.WebApi/Dockerfile
    ports:
      - "8080"
      - "8081"