services:
  myshoppinglist.webapi:
    image: ${DOCKER_REGISTRY-}myshoppinglistwebapi
    build:
      context: .
      dockerfile: MyShoppingList.WebApi/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: 8080
      ASPNETCORE_HTTPS_PORTS: 8081
      CONNECTIONSTRINGS__POSTGRES: ${DB_CONNECTIONSTRING}
    ports:
      - "5000:8080"
      - "5001:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  myshoppinglist.db:
  
  myshoppinglist.db:
    image: postgres:latest
    ports:
      - "6000:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ${USERPROFILE}/.containers/myshoppinglistdevdb:/var/lib/postgresql/data