# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Get solution file
      run: sln=$(ls *.sln 2>/dev/null); [ "$(echo "$sln" | wc -l)" -eq 1 ] && echo "$sln" || { echo "Expected exactly one .sln file, found $(echo "$sln" | wc -l)." >&2; exit 1; } >> $SOLUTION_FILE
    - name: Restore dependencies
      run: dotnet restore $SOLUTION_FILE
    - name: Build
      run: dotnet build $SOLUTION_FILE --no-restore
    - name: Test
      run: dotnet test $SOLUTION_FILE --no-build --verbosity normal
